version: "2.2"
services:
  server:
    init: true
    image: httpd:2.4.41-alpine
    ports:
      - 8000:80
    volumes:
      - $PWD:/usr/local/apache2/htdocs
  assets:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./assets:/app
    command: sh ./run-grunt.sh
